// src/Research/FinalSummary.jsx
import React, { useContext, useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

import AnonymousHeader from './AnonymousHeader';
import Footer from '../layout/Footer';
import { ThemeContext, ThemeProvider } from '../DarkLightMood/ThemeContext';
import { useAnonymousStudent as useStudent } from '../context/AnonymousStudentContext';
import ProgressSteps from './ProgressSteps';
// ✅ i18n
import { useI18n } from '../utils/i18n';

function FinalSummaryInner() {
  const { theme } = useContext(ThemeContext);
  const isDark = theme === 'dark';
  const { student } = useStudent?.() || { student: null };
  const navigate = useNavigate();
  const location = useLocation();
useEffect(() => {
  // ✅ ביטול נעילת שפה אם המשתמש חזר לדף שבו לא אמורה להיות נעילה
  try {
    const lock = localStorage.getItem("langLock");
    if (lock === "1") {
      localStorage.removeItem("langLock");
      window.dispatchEvent(new Event("lang-lock-change"));
      console.log("Language lock removed on this page");
    }
  } catch (e) {
    console.warn("Failed to clear langLock:", e);
  }
}, []);

  // ---- i18n ----
  const { t, dir, lang: langAttr, ready } = useI18n('finalSummary');

  const anonId = location.state?.anonId || student?.anonId || null;

  // Prefer summary passed via navigation state (already generated by previous page)
  const [summary, setSummary] = useState(location.state?.summaryText || '');
  const [loading, setLoading] = useState(!summary);
  const [err, setErr] = useState('');
const remainingLabel =
  langAttr === 'he' ? 'נשארו 3 שלבים' : '3 steps left';

const remainingItems =
  langAttr === 'he'
    ? [
        { n: 1, text: 'Post-CASEL' },
        { n: 2, text: 'רפלקציה' },
        { n: 3, text: 'UEQ-S' },
      ]
    : [
        { n: 1, text: 'Post-CASEL' },
        { n: 2, text: 'Reflection' },
        { n: 3, text: 'UEQ-S' },
      ];
  useEffect(() => {
    // If we already have the summary via state, do nothing
    if (summary) return;

    // Otherwise, fetch the saved summary from DB (GET), no AI calls here
    (async () => {
      try {
        if (!anonId) { setErr(t('missingAnonId')); setLoading(false); return; }
        setLoading(true); setErr('');

        const resp = await fetch(`/api/trial/summary/${encodeURIComponent(anonId)}`, {
          method: 'GET'
        });
        const data = await resp.json();
        if (!resp.ok || !data?.ok) throw new Error(data?.error || t('loadFailed'));

        setSummary(data.aiConversationSummary || '');
      } catch (e) {
        setErr(e.message || t('loadError'));
      } finally {
        setLoading(false);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [anonId, summary]); // שומרים על אותו דפוס ולא "שוברים" לוגיקה

  // כדי למנוע הבהוב טקסטים לפני טעינת המילון
  if (!ready) return null;

return (
    <div
      className={`flex flex-col min-h-screen w-screen ${
        isDark ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-800'
      }`}
      dir={dir}
      lang={langAttr}
      style={{
        fontFamily:
          'Heebo, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      }}
    >

      {/* HEADER */}
      <div className="px-4 mt-4">
        <AnonymousHeader />
      </div>

      {/* BODY */}
      <main className="flex-1 w-full px-3 md:px-5 lg:px-6 py-6">
      <div className="mb-4 sm:mb-6">
<ProgressSteps
  groupType="experiment"
  currentStep={5}
  language={langAttr}
  isDark={isDark}
/>
</div>
        <section className={`${isDark ? 'bg-slate-700' : 'bg-slate-200'} p-6 md:p-7 rounded`}>
        
          <div className={`rounded-lg shadow-md p-6 md:p-8 ${isDark ? 'bg-slate-600' : 'bg-white'} max-w-6xl mx-auto`}>
            {/* Thank You header inside the card */}
            <div className="mb-6 text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-emerald-500 mb-4 mx-auto">
                <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className={`clear-both text-3xl md:text-4xl font-bold mb-2 ${isDark ? 'text-white' : 'text-slate-800'}`}>
                {t('thanksTitle')}
              </h2>
              <p className={`${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
                {t('thanksSub')}
              </p>
            </div>

            {/* Content Area */}
            <div className="px-2 md:px-4 py-4">
              {loading && (
                <div className="flex flex-col items-center justify-center py-16" role="status" aria-live="polite">
                  <div className="relative">
                    <div className={`w-16 h-16 border-4 rounded-full animate-spin ${isDark ? 'border-slate-600 border-t-emerald-400' : 'border-slate-200 border-t-emerald-600'}`} />
                    <div className={`absolute inset-0 w-16 h-16 border-4 rounded-full animate-ping opacity-20 ${isDark ? 'border-emerald-400' : 'border-emerald-600'}`} />
                  </div>
                  <p className={`mt-6 text-base font-medium ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
                    {t('loading')}
                  </p>
                </div>
              )}

              {err && (
                <div className={`rounded-xl p-6 text-center ${isDark ? 'bg-red-900/30 border-2 border-red-800' : 'bg-red-50 border-2 border-red-200'}`}>
                  <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-red-500 mb-4">
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </div>
                  <div className={`text-lg font-semibold mb-4 ${isDark ? 'text-red-300' : 'text-red-700'}`}>
                    {err}
                  </div>
                  <button
                    onClick={() => navigate('/study/home')}
                    className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-xl transition-all duration-200 shadow-lg hover:shadow-xl"
                  >
                    {t('back')}
                  </button>
                </div>
              )}
{!loading && !err && (
  <div className="space-y-8">
   {/* Remaining Steps Bar */}
<div
  dir={dir}
  className={`rounded-full border px-4 py-3 ${
    isDark
      ? 'bg-sky-900/20 border-sky-700'
      : 'bg-sky-50 border-sky-200'
  }`}
>
<div
className="flex flex-wrap items-center justify-center gap-2 text-center"
>
    <span
      className={`inline-flex items-center rounded-full px-3 py-1 text-sm font-semibold ${
        isDark
          ? 'bg-blue-600 text-white'
          : 'bg-blue-500 text-white'
      }`}
    >
      {langAttr === 'he' ? '←' : '→'} {remainingLabel}
    </span>

    {remainingItems.map((item, index) => (
      <React.Fragment key={item.n}>
        <span className={`${isDark ? 'text-slate-300' : 'text-slate-500'}`}>
          {index > 0 ? '•' : ''}
        </span>
<span
  className={`inline-flex items-center gap-1 text-sm font-medium ${
    isDark ? 'text-slate-100' : 'text-slate-700'
  }`}
>
  <span
    className={`inline-flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold ${
      isDark
        ? 'bg-blue-600 text-white'
        : 'bg-blue-600 text-white'
    }`}
  >
    {item.n}
  </span>
  <span>{item.text}</span>
</span>
      </React.Fragment>
    ))}
  </div>
</div>

    {/* Summary Section */}
                  <div className={`rounded-xl p-6 md:p-8 ${isDark ? 'bg-slate-900/50 border border-slate-600' : 'bg-slate-50 border border-slate-200'}`}>
                    <div className={`flex items-center gap-3 mb-4 ${dir === 'rtl' ? 'flex-row-reverse justify-end text-right' : ''}`}>
                      <div className={`w-1 h-8 rounded-full ${isDark ? 'bg-emerald-400' : 'bg-emerald-600'}`} />
                      <h3 className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-slate-800'}`}>
                        {t('summaryTitle')}
                      </h3>
                    </div>
                    <p className={`text-base md:text-lg leading-relaxed whitespace-pre-wrap ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
                      {summary || t('noSummary')}
                    </p>
                  </div>

                  {/* Action Button */}
                  <div className={`pt-2 text-center ${dir === 'rtl' ? 'md:text-right' : 'md:text-left'}`}>
                    <button
                      onClick={() =>
                        navigate('/validated-questionnaire', {
                          state: { phase: 'post', from: 'final-summary', anonId }
                        })
                      }
                      className={`w-full md:w-auto px-8 py-4 rounded-xl font-bold text-lg text-white transition-all duration-300 shadow-lg hover:shadow-2xl transform hover:-translate-y-0.5 ${
                        isDark
                          ? 'bg-gradient-to-r from-emerald-600 to-emerald-500 hover:from-emerald-500 hover:to-emerald-400'
                          : 'bg-gradient-to-r from-emerald-600 to-emerald-500 hover:from-emerald-700 hover:to-emerald-600'
                      }`}
                    >
                      {t('continueCta')}
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </section>
      </main>

      {/* FOOTER */}
      <div className="px-4 pb-4">
        <Footer />
      </div>
    </div>
  );
}

export default function FinalSummary() {
  return (
      <FinalSummaryInner />
  );
}
